name: Go CI
on:
  - push
  - pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m

  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"
    - run: go mod tidy
    - name: Run unit tests
      run: go test -v ./...
      
  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"
    - run: go mod tidy
    - name: Run integration tcp tests
      run: go run tests/integration/tcp/tcp.go
    - name: Run integration kcp tests
      run: go run tests/integration/kcp/kcp.go

  build:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"
    - run: go mod tidy
    - run: make build
